version: '2'

services:
  producer:
    image: samber/rabbitmq-flooding:latest
    build: .
    env_file: .env
    command: producer.py
    restart: unless-stopped

  consumer:
    image: samber/rabbitmq-flooding:latest
    build: .
    env_file: .env
    command: consumer.py
    restart: unless-stopped
