version: '2'

services:
  producer:
    image: samber/rabbitmq-flooding:latest
    build: .
    environment:
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_VHOST=/cluster-testing
      - RABBITMQ_QUEUE=hello
      - RABBITMQ_EXCHANGE=
      - RABBITMQ_ROUTING_KEY=
    command: producer.py
    restart: unless-stopped

  consumer:
    image: samber/rabbitmq-flooding:latest
    build: .
    environment:
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_VHOST=/cluster-testing
      - RABBITMQ_QUEUE=hello
      - RABBITMQ_EXCHANGE=
      - RABBITMQ_ROUTING_KEY=
    command: consumer.py
    restart: unless-stopped
